### ISSUE TITLE
崩溃了啊

### ISSUE THREAD

**Issue by nujnay** [djstava/VLCAndroidMultiWindow#1]
04-27 15:03:31.763 15986-15986/com.xugaoxiang.vlcandroidmultiwindow E/linker: /data/app/com.xugaoxiang.vlcandroidmultiwindow-2/lib/arm/libvlcjni.so: has text relocations
04-27 15:03:31.768 15986-15986/com.xugaoxiang.vlcandroidmultiwindow E/VLC/LibVLC/Util: Can't load vlcjni library: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.xugaoxiang.vlcandroidmultiwindow-2/lib/arm/libvlcjni.so: has text relocations

**Comment by djstava** [comment]
请提供下测试文件．
